/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_silverspoon_bulldog_linux_jni_NativeI2c */

#ifndef _Included_io_silverspoon_bulldog_linux_jni_NativeI2c
#define _Included_io_silverspoon_bulldog_linux_jni_NativeI2c
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeI2c
 * Method:    i2cRead
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeI2c_i2cRead
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeI2c
 * Method:    i2cWrite
 * Signature: (IB)I
 */
JNIEXPORT jint JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeI2c_i2cWrite
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeI2c
 * Method:    i2cSelectSlave
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeI2c_i2cSelectSlave
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeI2c
 * Method:    i2cOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeI2c_i2cOpen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_silverspoon_bulldog_linux_jni_NativeI2c
 * Method:    i2cClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_io_silverspoon_bulldog_linux_jni_NativeI2c_i2cClose
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
