/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bulldog_linux_jni_NativeEpoll */

#ifndef _Included_org_bulldog_linux_jni_NativeEpoll
#define _Included_org_bulldog_linux_jni_NativeEpoll
#ifdef __cplusplus
extern "C" {
#endif
#undef org_bulldog_linux_jni_NativeEpoll_EPOLLIN
#define org_bulldog_linux_jni_NativeEpoll_EPOLLIN 1L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLLPRI
#define org_bulldog_linux_jni_NativeEpoll_EPOLLPRI 2L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLLOUT
#define org_bulldog_linux_jni_NativeEpoll_EPOLLOUT 4L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLLRDNORM
#define org_bulldog_linux_jni_NativeEpoll_EPOLLRDNORM 64L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLLRDBAND
#define org_bulldog_linux_jni_NativeEpoll_EPOLLRDBAND 128L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLLWRNORM
#define org_bulldog_linux_jni_NativeEpoll_EPOLLWRNORM 256L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLLWRBAND
#define org_bulldog_linux_jni_NativeEpoll_EPOLLWRBAND 512L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLLMSG
#define org_bulldog_linux_jni_NativeEpoll_EPOLLMSG 1024L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLLERR
#define org_bulldog_linux_jni_NativeEpoll_EPOLLERR 8L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLLHUP
#define org_bulldog_linux_jni_NativeEpoll_EPOLLHUP 16L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLLRDHUP
#define org_bulldog_linux_jni_NativeEpoll_EPOLLRDHUP 8192L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLLWAKEUP
#define org_bulldog_linux_jni_NativeEpoll_EPOLLWAKEUP 536870912L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLLONESHOT
#define org_bulldog_linux_jni_NativeEpoll_EPOLLONESHOT 1073741824L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLLET
#define org_bulldog_linux_jni_NativeEpoll_EPOLLET -2147483648L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLL_CTL_ADD
#define org_bulldog_linux_jni_NativeEpoll_EPOLL_CTL_ADD 1L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLL_CTL_DEL
#define org_bulldog_linux_jni_NativeEpoll_EPOLL_CTL_DEL 2L
#undef org_bulldog_linux_jni_NativeEpoll_EPOLL_CTL_MOD
#define org_bulldog_linux_jni_NativeEpoll_EPOLL_CTL_MOD 3L
/*
 * Class:     org_bulldog_linux_jni_NativeEpoll
 * Method:    epollCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_bulldog_linux_jni_NativeEpoll_epollCreate
  (JNIEnv *, jclass);

/*
 * Class:     org_bulldog_linux_jni_NativeEpoll
 * Method:    addFile
 * Signature: (IILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_bulldog_linux_jni_NativeEpoll_addFile
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     org_bulldog_linux_jni_NativeEpoll
 * Method:    removeFile
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_bulldog_linux_jni_NativeEpoll_removeFile
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_bulldog_linux_jni_NativeEpoll
 * Method:    waitForInterrupt
 * Signature: (I)[Lorg/bulldog/linux/jni/NativePollResult;
 */
JNIEXPORT jobjectArray JNICALL Java_org_bulldog_linux_jni_NativeEpoll_waitForInterrupt
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_bulldog_linux_jni_NativeEpoll
 * Method:    stopWait
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_bulldog_linux_jni_NativeEpoll_stopWait
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_bulldog_linux_jni_NativeEpoll
 * Method:    shutdown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_bulldog_linux_jni_NativeEpoll_shutdown
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
